use_frameworks!
inhibit_all_warnings!     # 屏蔽pod中告警

platform :ios, '11.0'

target 'ZLGitRemoteService_Example' do
  pod 'ZLGitRemoteService', :path => '../'

  target 'ZLGitRemoteService_Tests' do
    inherit! :search_paths
  end
end
